# Fly.io configuration for backend deployment
app = "prompt2story"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 75

  # ✅ Health check must be nested under http_service and include "type"
  [[http_service.checks]]
    type = "http"
    method = "get"
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "20s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
