# Fly.io configuration for backend deployment
app = "prompt2story"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[checks]]
  type = "http"
  name = "healthz"
  port = 8000
  method = "get"
  path = "/healthz"
  interval = "15s"
  timeout = "5s"
  grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
