# Fly.io configuration for backend deployment
app = "prompt2story"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 75

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512  # bump to 1024 if you see OOM (exit 137)

# REMOVE the poetry install; use deploy command only for migrations if needed
# [deploy]
#   release_command = "alembic upgrade head"

[checks]
  [checks.http]
    port = 8000
    method = "get"
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "20s"
